//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevToys.Blazor.BuiltInTools.PasswordGenerator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PasswordGenerator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PasswordGenerator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevToys.Blazor.BuiltInTools.PasswordGenerator.PasswordGenerator", typeof(PasswordGenerator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Generator.
        /// </summary>
        internal static string AccessibleName {
            get {
                return ResourceManager.GetString("AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Types.
        /// </summary>
        internal static string CharacterTypesDescription {
            get {
                return ResourceManager.GetString("CharacterTypesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Types.
        /// </summary>
        internal static string CharacterTypesTitle {
            get {
                return ResourceManager.GetString("CharacterTypesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string ConfigurationSectionTitle {
            get {
                return ResourceManager.GetString("ConfigurationSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string CopyButtonText {
            get {
                return ResourceManager.GetString("CopyButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of passwords to generate (1-100).
        /// </summary>
        internal static string CountDescription {
            get {
                return ResourceManager.GetString("CountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Count.
        /// </summary>
        internal static string CountTitle {
            get {
                return ResourceManager.GetString("CountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate secure passwords with customizable options.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters to exclude from the generated password.
        /// </summary>
        internal static string ExcludeCharactersDescription {
            get {
                return ResourceManager.GetString("ExcludeCharactersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter characters to exclude....
        /// </summary>
        internal static string ExcludeCharactersPlaceholder {
            get {
                return ResourceManager.GetString("ExcludeCharactersPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude Characters.
        /// </summary>
        internal static string ExcludeCharactersTitle {
            get {
                return ResourceManager.GetString("ExcludeCharactersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string GenerateButtonText {
            get {
                return ResourceManager.GetString("GenerateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error generating password:.
        /// </summary>
        internal static string GenerationErrorPrefix {
            get {
                return ResourceManager.GetString("GenerationErrorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include digits (0-9).
        /// </summary>
        internal static string IncludeDigitsTitle {
            get {
                return ResourceManager.GetString("IncludeDigitsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include lowercase letters (a-z).
        /// </summary>
        internal static string IncludeLowercaseTitle {
            get {
                return ResourceManager.GetString("IncludeLowercaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include special characters (!@#$%^&*).
        /// </summary>
        internal static string IncludeSpecialTitle {
            get {
                return ResourceManager.GetString("IncludeSpecialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include uppercase letters (A-Z).
        /// </summary>
        internal static string IncludeUppercaseTitle {
            get {
                return ResourceManager.GetString("IncludeUppercaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the generated password (1-128 characters).
        /// </summary>
        internal static string LengthDescription {
            get {
                return ResourceManager.GetString("LengthDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Length.
        /// </summary>
        internal static string LengthTitle {
            get {
                return ResourceManager.GetString("LengthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Generator.
        /// </summary>
        internal static string LongDisplayTitle {
            get {
                return ResourceManager.GetString("LongDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No characters available for password generation. Please select at least one character type and ensure you haven't excluded all characters..
        /// </summary>
        internal static string NoCharactersAvailableError {
            get {
                return ResourceManager.GetString("NoCharactersAvailableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated passwords will appear here....
        /// </summary>
        internal static string OutputPlaceholder {
            get {
                return ResourceManager.GetString("OutputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated Passwords.
        /// </summary>
        internal static string OutputSectionTitle {
            get {
                return ResourceManager.GetString("OutputSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password;generate;random;secure;generator.
        /// </summary>
        internal static string SearchKeywords {
            get {
                return ResourceManager.GetString("SearchKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Generator.
        /// </summary>
        internal static string ShortDisplayTitle {
            get {
                return ResourceManager.GetString("ShortDisplayTitle", resourceCulture);
            }
        }
    }
}