
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

using Microsoft.Toolkit.Mvvm.ComponentModel;
using System.Collections.Generic;
using System.ComponentModel;
using System.Globalization;
using Windows.ApplicationModel.Resources;
using Windows.Globalization;
using Windows.UI.Xaml;

namespace DevToys
{
    public partial class LanguageManager : ObservableObject
    {
        private static LanguageManager? _languageManager;

        private readonly AllToolsStrings _alltools = new AllToolsStrings();
        private readonly CommonStrings _common = new CommonStrings();
        private readonly JsonFormatterStrings _jsonformatter = new JsonFormatterStrings();
        private readonly MainPageStrings _mainpage = new MainPageStrings();
        private readonly SearchResultStrings _searchresult = new SearchResultStrings();
        private readonly SettingsStrings _settings = new SettingsStrings();
        private readonly ToolGroupsStrings _toolgroups = new ToolGroupsStrings();

        /// <summary>
        /// Gets an instance of <see cref="LanguageManager"/>.
        /// </summary>
        public static LanguageManager Instance => _languageManager ?? (_languageManager = new LanguageManager());

        /// <summary>
        /// Gets if the text must be written from left to right or from right to left.
        /// </summary>
        public FlowDirection FlowDirection { get; private set; }

        /// <summary>
        /// Gets the <see cref="AllToolsStrings"/>.
        /// </summary>
        public AllToolsStrings AllTools => _alltools;

        /// <summary>
        /// Gets the <see cref="CommonStrings"/>.
        /// </summary>
        public CommonStrings Common => _common;

        /// <summary>
        /// Gets the <see cref="JsonFormatterStrings"/>.
        /// </summary>
        public JsonFormatterStrings JsonFormatter => _jsonformatter;

        /// <summary>
        /// Gets the <see cref="MainPageStrings"/>.
        /// </summary>
        public MainPageStrings MainPage => _mainpage;

        /// <summary>
        /// Gets the <see cref="SearchResultStrings"/>.
        /// </summary>
        public SearchResultStrings SearchResult => _searchresult;

        /// <summary>
        /// Gets the <see cref="SettingsStrings"/>.
        /// </summary>
        public SettingsStrings Settings => _settings;

        /// <summary>
        /// Gets the <see cref="ToolGroupsStrings"/>.
        /// </summary>
        public ToolGroupsStrings ToolGroups => _toolgroups;

        /// <summary>
        /// Gets the list of available languages in the app.
        /// </summary>
        public List<LanguageDefinition> AvailableLanguages { get; }

        public LanguageManager()
        {
            AvailableLanguages = new List<LanguageDefinition>();
            AvailableLanguages.Add(new LanguageDefinition()); // default language
            IReadOnlyList<string> supportedLanguageIdentifiers = ApplicationLanguages.ManifestLanguages;
            for (int i = 0; i < supportedLanguageIdentifiers.Count; i++)
            {
                AvailableLanguages.Add(new LanguageDefinition(supportedLanguageIdentifiers[i]));
            }
        }

        /// <summary>
        /// Retrieves the current culture.
        /// </summary>
        public CultureInfo GetCurrentCulture()
        {
            return CultureInfo.CurrentUICulture;
        }

        /// <summary>
        /// Change the current culture of the application
        /// </summary>
        public void SetCurrentCulture(LanguageDefinition language)
        {
            CultureInfo.DefaultThreadCurrentCulture = language.Culture;
            CultureInfo.DefaultThreadCurrentUICulture = language.Culture;
            ApplicationLanguages.PrimaryLanguageOverride = language.Identifier;

            if (language.Culture.TextInfo.IsRightToLeft)
            {
                FlowDirection = FlowDirection.RightToLeft;
            }
            else
            {
                FlowDirection = FlowDirection.LeftToRight;
            }

            // All the properties changed.
            OnPropertyChanged(new PropertyChangedEventArgs(string.Empty));
        }
    }

    public class AllToolsStrings : ObservableObject
    {
        private readonly ResourceLoader _resources = ResourceLoader.GetForViewIndependentUse("AllTools");

        /// <summary>
        /// Gets the resource AccessibleName.
        /// </summary>
        public string AccessibleName => _resources.GetString("AccessibleName");

        /// <summary>
        /// Gets the resource MenuDisplayName.
        /// </summary>
        public string MenuDisplayName => _resources.GetString("MenuDisplayName");
    }

    public class CommonStrings : ObservableObject
    {
        private readonly ResourceLoader _resources = ResourceLoader.GetForViewIndependentUse("Common");

        /// <summary>
        /// Gets the resource Bytes.
        /// </summary>
        public string Bytes => _resources.GetString("Bytes");

        /// <summary>
        /// Gets the resource Clear.
        /// </summary>
        public string Clear => _resources.GetString("Clear");

        /// <summary>
        /// Gets the resource Collapse.
        /// </summary>
        public string Collapse => _resources.GetString("Collapse");

        /// <summary>
        /// Gets the resource Copy.
        /// </summary>
        public string Copy => _resources.GetString("Copy");

        /// <summary>
        /// Gets the resource Cut.
        /// </summary>
        public string Cut => _resources.GetString("Cut");

        /// <summary>
        /// Gets the resource Delete.
        /// </summary>
        public string Delete => _resources.GetString("Delete");

        /// <summary>
        /// Gets the resource Expand.
        /// </summary>
        public string Expand => _resources.GetString("Expand");

        /// <summary>
        /// Gets the resource ShowInfo.
        /// </summary>
        public string ShowInfo => _resources.GetString("ShowInfo");

        /// <summary>
        /// Gets the resource HideInfo.
        /// </summary>
        public string HideInfo => _resources.GetString("HideInfo");

        /// <summary>
        /// Gets the resource FileSelectorBrowseFiles.
        /// </summary>
        public string FileSelectorBrowseFiles => _resources.GetString("FileSelectorBrowseFiles");

        /// <summary>
        /// Gets the resource FileSelectorBrowseFolders.
        /// </summary>
        public string FileSelectorBrowseFolders => _resources.GetString("FileSelectorBrowseFolders");

        /// <summary>
        /// Gets the resource FileSelectorDragDropAnyFile.
        /// </summary>
        public string FileSelectorDragDropAnyFile => _resources.GetString("FileSelectorDragDropAnyFile");

        /// <summary>
        /// Gets the resource FileSelectorDragDropAnyFiles.
        /// </summary>
        public string FileSelectorDragDropAnyFiles => _resources.GetString("FileSelectorDragDropAnyFiles");

        /// <summary>
        /// Gets the resource FileSelectorDragDropAnySpecificFile.
        /// </summary>
        public string FileSelectorDragDropAnySpecificFile => _resources.GetString("FileSelectorDragDropAnySpecificFile");

        /// <summary>
        /// Gets the resource FileSelectorDragDropAnySpecificFile with format.
        /// </summary>
        public string GetFormattedFileSelectorDragDropAnySpecificFile(string? param0)
        {
            return string.Format(FileSelectorDragDropAnySpecificFile, param0);
        }

        /// <summary>
        /// Gets the resource FileSelectorDragDropAnySpecificFiles.
        /// </summary>
        public string FileSelectorDragDropAnySpecificFiles => _resources.GetString("FileSelectorDragDropAnySpecificFiles");

        /// <summary>
        /// Gets the resource FileSelectorDragDropAnySpecificFiles with format.
        /// </summary>
        public string GetFormattedFileSelectorDragDropAnySpecificFiles(string? param0)
        {
            return string.Format(FileSelectorDragDropAnySpecificFiles, param0);
        }

        /// <summary>
        /// Gets the resource FileSelectorInvalidSelectedFiles.
        /// </summary>
        public string FileSelectorInvalidSelectedFiles => _resources.GetString("FileSelectorInvalidSelectedFiles");

        /// <summary>
        /// Gets the resource FileSelectorInvalidSelectedFiles with format.
        /// </summary>
        public string GetFormattedFileSelectorInvalidSelectedFiles(string? param0)
        {
            return string.Format(FileSelectorInvalidSelectedFiles, param0);
        }

        /// <summary>
        /// Gets the resource FileSelectorOr.
        /// </summary>
        public string FileSelectorOr => _resources.GetString("FileSelectorOr");

        /// <summary>
        /// Gets the resource Gigabytes.
        /// </summary>
        public string Gigabytes => _resources.GetString("Gigabytes");

        /// <summary>
        /// Gets the resource Kilobytes.
        /// </summary>
        public string Kilobytes => _resources.GetString("Kilobytes");

        /// <summary>
        /// Gets the resource Megabytes.
        /// </summary>
        public string Megabytes => _resources.GetString("Megabytes");

        /// <summary>
        /// Gets the resource Ok.
        /// </summary>
        public string Ok => _resources.GetString("Ok");

        /// <summary>
        /// Gets the resource OpenFile.
        /// </summary>
        public string OpenFile => _resources.GetString("OpenFile");

        /// <summary>
        /// Gets the resource Paste.
        /// </summary>
        public string Paste => _resources.GetString("Paste");

        /// <summary>
        /// Gets the resource Redo.
        /// </summary>
        public string Redo => _resources.GetString("Redo");

        /// <summary>
        /// Gets the resource Refresh.
        /// </summary>
        public string Refresh => _resources.GetString("Refresh");

        /// <summary>
        /// Gets the resource SaveAs.
        /// </summary>
        public string SaveAs => _resources.GetString("SaveAs");

        /// <summary>
        /// Gets the resource SelectAll.
        /// </summary>
        public string SelectAll => _resources.GetString("SelectAll");

        /// <summary>
        /// Gets the resource Terabytes.
        /// </summary>
        public string Terabytes => _resources.GetString("Terabytes");

        /// <summary>
        /// Gets the resource ToggleSwitchOff.
        /// </summary>
        public string ToggleSwitchOff => _resources.GetString("ToggleSwitchOff");

        /// <summary>
        /// Gets the resource ToggleSwitchOn.
        /// </summary>
        public string ToggleSwitchOn => _resources.GetString("ToggleSwitchOn");

        /// <summary>
        /// Gets the resource UnableOpenFile.
        /// </summary>
        public string UnableOpenFile => _resources.GetString("UnableOpenFile");

        /// <summary>
        /// Gets the resource UnableOpenFileDescription.
        /// </summary>
        public string UnableOpenFileDescription => _resources.GetString("UnableOpenFileDescription");

        /// <summary>
        /// Gets the resource UnableOpenFileDescription with format.
        /// </summary>
        public string GetFormattedUnableOpenFileDescription(string? param0)
        {
            return string.Format(UnableOpenFileDescription, param0);
        }

        /// <summary>
        /// Gets the resource Undo.
        /// </summary>
        public string Undo => _resources.GetString("Undo");

        /// <summary>
        /// Gets the resource ViewImage.
        /// </summary>
        public string ViewImage => _resources.GetString("ViewImage");
    }

    public class JsonFormatterStrings : ObservableObject
    {
        private readonly ResourceLoader _resources = ResourceLoader.GetForViewIndependentUse("JsonFormatter");

        /// <summary>
        /// Gets the resource AccessibleName.
        /// </summary>
        public string AccessibleName => _resources.GetString("AccessibleName");

        /// <summary>
        /// Gets the resource Configuration.
        /// </summary>
        public string Configuration => _resources.GetString("Configuration");

        /// <summary>
        /// Gets the resource MenuDisplayName.
        /// </summary>
        public string MenuDisplayName => _resources.GetString("MenuDisplayName");

        /// <summary>
        /// Gets the resource FourSpaces.
        /// </summary>
        public string FourSpaces => _resources.GetString("FourSpaces");

        /// <summary>
        /// Gets the resource Indentation.
        /// </summary>
        public string Indentation => _resources.GetString("Indentation");

        /// <summary>
        /// Gets the resource Input.
        /// </summary>
        public string Input => _resources.GetString("Input");

        /// <summary>
        /// Gets the resource Minified.
        /// </summary>
        public string Minified => _resources.GetString("Minified");

        /// <summary>
        /// Gets the resource OneTab.
        /// </summary>
        public string OneTab => _resources.GetString("OneTab");

        /// <summary>
        /// Gets the resource Output.
        /// </summary>
        public string Output => _resources.GetString("Output");

        /// <summary>
        /// Gets the resource TwoSpaces.
        /// </summary>
        public string TwoSpaces => _resources.GetString("TwoSpaces");

        /// <summary>
        /// Gets the resource Description.
        /// </summary>
        public string Description => _resources.GetString("Description");

        /// <summary>
        /// Gets the resource SearchDisplayName.
        /// </summary>
        public string SearchDisplayName => _resources.GetString("SearchDisplayName");

        /// <summary>
        /// Gets the resource SearchKeywords.
        /// </summary>
        public string SearchKeywords => _resources.GetString("SearchKeywords");

        /// <summary>
        /// Gets the resource SortProperties.
        /// </summary>
        public string SortProperties => _resources.GetString("SortProperties");
    }

    public class MainPageStrings : ObservableObject
    {
        private readonly ResourceLoader _resources = ResourceLoader.GetForViewIndependentUse("MainPage");

        /// <summary>
        /// Gets the resource AddToFavorites.
        /// </summary>
        public string AddToFavorites => _resources.GetString("AddToFavorites");

        /// <summary>
        /// Gets the resource EnterCompactOverlayTooltip.
        /// </summary>
        public string EnterCompactOverlayTooltip => _resources.GetString("EnterCompactOverlayTooltip");

        /// <summary>
        /// Gets the resource ExitCompactOverlayTooltip.
        /// </summary>
        public string ExitCompactOverlayTooltip => _resources.GetString("ExitCompactOverlayTooltip");

        /// <summary>
        /// Gets the resource NotificationRateAppActionableActionText.
        /// </summary>
        public string NotificationRateAppActionableActionText => _resources.GetString("NotificationRateAppActionableActionText");

        /// <summary>
        /// Gets the resource NotificationRateAppMessage.
        /// </summary>
        public string NotificationRateAppMessage => _resources.GetString("NotificationRateAppMessage");

        /// <summary>
        /// Gets the resource NotificationRateAppTitle.
        /// </summary>
        public string NotificationRateAppTitle => _resources.GetString("NotificationRateAppTitle");

        /// <summary>
        /// Gets the resource NotificationReleaseNoteActionableActionText.
        /// </summary>
        public string NotificationReleaseNoteActionableActionText => _resources.GetString("NotificationReleaseNoteActionableActionText");

        /// <summary>
        /// Gets the resource NotificationReleaseNoteTitle.
        /// </summary>
        public string NotificationReleaseNoteTitle => _resources.GetString("NotificationReleaseNoteTitle");

        /// <summary>
        /// Gets the resource NotificationReleaseNoteTitle with format.
        /// </summary>
        public string GetFormattedNotificationReleaseNoteTitle(string? param0)
        {
            return string.Format(NotificationReleaseNoteTitle, param0);
        }

        /// <summary>
        /// Gets the resource NotificationUpdateAvailableActionableActionText.
        /// </summary>
        public string NotificationUpdateAvailableActionableActionText => _resources.GetString("NotificationUpdateAvailableActionableActionText");

        /// <summary>
        /// Gets the resource NotificationUpdateAvailableTitle.
        /// </summary>
        public string NotificationUpdateAvailableTitle => _resources.GetString("NotificationUpdateAvailableTitle");

        /// <summary>
        /// Gets the resource OpenInNewWindow.
        /// </summary>
        public string OpenInNewWindow => _resources.GetString("OpenInNewWindow");

        /// <summary>
        /// Gets the resource PinToolToStart.
        /// </summary>
        public string PinToolToStart => _resources.GetString("PinToolToStart");

        /// <summary>
        /// Gets the resource PinToolToStartProblem.
        /// </summary>
        public string PinToolToStartProblem => _resources.GetString("PinToolToStartProblem");

        /// <summary>
        /// Gets the resource RemoveFromFavorites.
        /// </summary>
        public string RemoveFromFavorites => _resources.GetString("RemoveFromFavorites");

        /// <summary>
        /// Gets the resource Search.
        /// </summary>
        public string Search => _resources.GetString("Search");

        /// <summary>
        /// Gets the resource SearchNoResultsFound.
        /// </summary>
        public string SearchNoResultsFound => _resources.GetString("SearchNoResultsFound");

        /// <summary>
        /// Gets the resource SurveyDescription.
        /// </summary>
        public string SurveyDescription => _resources.GetString("SurveyDescription");

        /// <summary>
        /// Gets the resource SurveyTitle.
        /// </summary>
        public string SurveyTitle => _resources.GetString("SurveyTitle");

        /// <summary>
        /// Gets the resource SurveyYesButton.
        /// </summary>
        public string SurveyYesButton => _resources.GetString("SurveyYesButton");

        /// <summary>
        /// Gets the resource WindowTitle.
        /// </summary>
        public string WindowTitle => _resources.GetString("WindowTitle");

        /// <summary>
        /// Gets the resource WindowTitleWithToolName.
        /// </summary>
        public string WindowTitleWithToolName => _resources.GetString("WindowTitleWithToolName");

        /// <summary>
        /// Gets the resource WindowTitleWithToolName with format.
        /// </summary>
        public string GetFormattedWindowTitleWithToolName(string? param0)
        {
            return string.Format(WindowTitleWithToolName, param0);
        }
    }

    public class SearchResultStrings : ObservableObject
    {
        private readonly ResourceLoader _resources = ResourceLoader.GetForViewIndependentUse("SearchResult");

        /// <summary>
        /// Gets the resource SearchResults.
        /// </summary>
        public string SearchResults => _resources.GetString("SearchResults");

        /// <summary>
        /// Gets the resource SearchResults with format.
        /// </summary>
        public string GetFormattedSearchResults(string? param0)
        {
            return string.Format(SearchResults, param0);
        }

        /// <summary>
        /// Gets the resource NoResultsFound.
        /// </summary>
        public string NoResultsFound => _resources.GetString("NoResultsFound");
    }

    public class SettingsStrings : ObservableObject
    {
        private readonly ResourceLoader _resources = ResourceLoader.GetForViewIndependentUse("Settings");

        /// <summary>
        /// Gets the resource About.
        /// </summary>
        public string About => _resources.GetString("About");

        /// <summary>
        /// Gets the resource AppTheme.
        /// </summary>
        public string AppTheme => _resources.GetString("AppTheme");

        /// <summary>
        /// Gets the resource AppThemeDescription.
        /// </summary>
        public string AppThemeDescription => _resources.GetString("AppThemeDescription");

        /// <summary>
        /// Gets the resource AppTitle.
        /// </summary>
        public string AppTitle => _resources.GetString("AppTitle");

        /// <summary>
        /// Gets the resource Behaviors.
        /// </summary>
        public string Behaviors => _resources.GetString("Behaviors");

        /// <summary>
        /// Gets the resource Close.
        /// </summary>
        public string Close => _resources.GetString("Close");

        /// <summary>
        /// Gets the resource Copy.
        /// </summary>
        public string Copy => _resources.GetString("Copy");

        /// <summary>
        /// Gets the resource Dark.
        /// </summary>
        public string Dark => _resources.GetString("Dark");

        /// <summary>
        /// Gets the resource DefaultLanguage.
        /// </summary>
        public string DefaultLanguage => _resources.GetString("DefaultLanguage");

        /// <summary>
        /// Gets the resource MenuDisplayName.
        /// </summary>
        public string MenuDisplayName => _resources.GetString("MenuDisplayName");

        /// <summary>
        /// Gets the resource Font.
        /// </summary>
        public string Font => _resources.GetString("Font");

        /// <summary>
        /// Gets the resource HighlightCurrentLine.
        /// </summary>
        public string HighlightCurrentLine => _resources.GetString("HighlightCurrentLine");

        /// <summary>
        /// Gets the resource HighlightCurrentLineDescription.
        /// </summary>
        public string HighlightCurrentLineDescription => _resources.GetString("HighlightCurrentLineDescription");

        /// <summary>
        /// Gets the resource Language.
        /// </summary>
        public string Language => _resources.GetString("Language");

        /// <summary>
        /// Gets the resource LanguageDescription.
        /// </summary>
        public string LanguageDescription => _resources.GetString("LanguageDescription");

        /// <summary>
        /// Gets the resource License.
        /// </summary>
        public string License => _resources.GetString("License");

        /// <summary>
        /// Gets the resource Light.
        /// </summary>
        public string Light => _resources.GetString("Light");

        /// <summary>
        /// Gets the resource LineNumbers.
        /// </summary>
        public string LineNumbers => _resources.GetString("LineNumbers");

        /// <summary>
        /// Gets the resource LineNumbersDescription.
        /// </summary>
        public string LineNumbersDescription => _resources.GetString("LineNumbersDescription");

        /// <summary>
        /// Gets the resource OpenLogs.
        /// </summary>
        public string OpenLogs => _resources.GetString("OpenLogs");

        /// <summary>
        /// Gets the resource PrivacyPolicy.
        /// </summary>
        public string PrivacyPolicy => _resources.GetString("PrivacyPolicy");

        /// <summary>
        /// Gets the resource RateAndReview.
        /// </summary>
        public string RateAndReview => _resources.GetString("RateAndReview");

        /// <summary>
        /// Gets the resource RenderWhitespace.
        /// </summary>
        public string RenderWhitespace => _resources.GetString("RenderWhitespace");

        /// <summary>
        /// Gets the resource ReportProblem.
        /// </summary>
        public string ReportProblem => _resources.GetString("ReportProblem");

        /// <summary>
        /// Gets the resource SmartDetection.
        /// </summary>
        public string SmartDetection => _resources.GetString("SmartDetection");

        /// <summary>
        /// Gets the resource SmartDetectionDescription.
        /// </summary>
        public string SmartDetectionDescription => _resources.GetString("SmartDetectionDescription");

        /// <summary>
        /// Gets the resource SmartDetectionHowTo.
        /// </summary>
        public string SmartDetectionHowTo => _resources.GetString("SmartDetectionHowTo");

        /// <summary>
        /// Gets the resource SmartDetectionPaste.
        /// </summary>
        public string SmartDetectionPaste => _resources.GetString("SmartDetectionPaste");

        /// <summary>
        /// Gets the resource SourceCode.
        /// </summary>
        public string SourceCode => _resources.GetString("SourceCode");

        /// <summary>
        /// Gets the resource TextEditor.
        /// </summary>
        public string TextEditor => _resources.GetString("TextEditor");

        /// <summary>
        /// Gets the resource ThirdPartyNotices.
        /// </summary>
        public string ThirdPartyNotices => _resources.GetString("ThirdPartyNotices");

        /// <summary>
        /// Gets the resource UsefulLinks.
        /// </summary>
        public string UsefulLinks => _resources.GetString("UsefulLinks");

        /// <summary>
        /// Gets the resource UseSystemSettings.
        /// </summary>
        public string UseSystemSettings => _resources.GetString("UseSystemSettings");

        /// <summary>
        /// Gets the resource Version.
        /// </summary>
        public string Version => _resources.GetString("Version");

        /// <summary>
        /// Gets the resource Version with format.
        /// </summary>
        public string GetFormattedVersion(string? param0)
        {
            return string.Format(Version, param0);
        }

        /// <summary>
        /// Gets the resource WordWrap.
        /// </summary>
        public string WordWrap => _resources.GetString("WordWrap");

        /// <summary>
        /// Gets the resource Description.
        /// </summary>
        public string Description => _resources.GetString("Description");

        /// <summary>
        /// Gets the resource SearchDisplayName.
        /// </summary>
        public string SearchDisplayName => _resources.GetString("SearchDisplayName");

        /// <summary>
        /// Gets the resource SearchKeywords.
        /// </summary>
        public string SearchKeywords => _resources.GetString("SearchKeywords");

        /// <summary>
        /// Gets the resource HelpTranslating.
        /// </summary>
        public string HelpTranslating => _resources.GetString("HelpTranslating");

        /// <summary>
        /// Gets the resource PasteClearsText.
        /// </summary>
        public string PasteClearsText => _resources.GetString("PasteClearsText");

        /// <summary>
        /// Gets the resource PasteClearsTextDescription.
        /// </summary>
        public string PasteClearsTextDescription => _resources.GetString("PasteClearsTextDescription");
    }

    public class ToolGroupsStrings : ObservableObject
    {
        private readonly ResourceLoader _resources = ResourceLoader.GetForViewIndependentUse("ToolGroups");

        /// <summary>
        /// Gets the resource ConvertersAccessibleName.
        /// </summary>
        public string ConvertersAccessibleName => _resources.GetString("ConvertersAccessibleName");

        /// <summary>
        /// Gets the resource ConvertersDisplayName.
        /// </summary>
        public string ConvertersDisplayName => _resources.GetString("ConvertersDisplayName");

        /// <summary>
        /// Gets the resource EncodersDecodersAccessibleName.
        /// </summary>
        public string EncodersDecodersAccessibleName => _resources.GetString("EncodersDecodersAccessibleName");

        /// <summary>
        /// Gets the resource EncodersDecodersDisplayName.
        /// </summary>
        public string EncodersDecodersDisplayName => _resources.GetString("EncodersDecodersDisplayName");

        /// <summary>
        /// Gets the resource FormattersAccessibleName.
        /// </summary>
        public string FormattersAccessibleName => _resources.GetString("FormattersAccessibleName");

        /// <summary>
        /// Gets the resource FormattersDisplayName.
        /// </summary>
        public string FormattersDisplayName => _resources.GetString("FormattersDisplayName");

        /// <summary>
        /// Gets the resource GeneratorsAccessibleName.
        /// </summary>
        public string GeneratorsAccessibleName => _resources.GetString("GeneratorsAccessibleName");

        /// <summary>
        /// Gets the resource GeneratorsDisplayName.
        /// </summary>
        public string GeneratorsDisplayName => _resources.GetString("GeneratorsDisplayName");

        /// <summary>
        /// Gets the resource GraphicAccessibleName.
        /// </summary>
        public string GraphicAccessibleName => _resources.GetString("GraphicAccessibleName");

        /// <summary>
        /// Gets the resource GraphicDisplayName.
        /// </summary>
        public string GraphicDisplayName => _resources.GetString("GraphicDisplayName");

        /// <summary>
        /// Gets the resource TextAccessibleName.
        /// </summary>
        public string TextAccessibleName => _resources.GetString("TextAccessibleName");

        /// <summary>
        /// Gets the resource TextDisplayName.
        /// </summary>
        public string TextDisplayName => _resources.GetString("TextDisplayName");
    }
}
